spring.application.name=task-management-application

spring.datasource.url=jdbc:mysql://localhost:3306/task_management_application\
?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=gRw100HDRas900/MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG

logging.level.org.springframework.security=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

spring.mvc.log-request-details=true

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jackson.time-zone=UTC

spring.messages.basename=messages
spring.messages.encoding=UTF-8

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

dropbox.access-token=sl.u.AGPpcCAbGqpg3PokA7mEci_dC8NTphoE75gjzP_VIF3pMg--KGIJpGA2v1gvs1SVLj4emhzNOIjhJ477Zgw5VApE9OeVUEQmxp_fiyVhXLGlXNiz1SYO_vgSGaKgBP8TPW6IBHvJRzs7FHZgMjS78_jIivmBNOxiduAZSYgPGp-BGuKLxwPWqpBjk0J6Ir8gg0bcGPlQtalurIWv2Gn8CEg4bC0OxzTYkqoHjKlx8L8uPYFimm8dsRGakwIBjvpCYRLhOgo5MKhZkvOA-zRKfe8IYXMDlJmid3lUQCkM7eLZSKp9c_Vm0yS7CD6uef0Q5j0qU_1eR8S5QQf4AnNiDURBuCUKTzN8du5Ia2tuPa2ECQU--vPjZA5qCKs12lLZcMzhh_TqfUA_rdjExCFQiImu3qluXw7apgC4HltntGmpeUDgrez7EVYCf56HeCE8RIKesz4Eig5BXrk4DtsDwEvzuKPSlPTDOq3VP8C-hyr3H2KGKewa3l1opKb7sIYv3hI31N9CwOfXhZhCdTrUpnMFilzkjpjCRITPuELM9RNadfP6JTJiNn45aSGY3p0oMrAIBQsAIvBb1FonKm40l7OQW3LZejc7GGjlLubtQzRgzMGZTPxBbuhtpwwcC6XmTg3URI0homir0d1xQ5RZlAyvtXKXhnP7ETq0J_egnW08rJyWiYZtxKJohqOYYTuMjRwW1UdH8_kKynYX7sC-3JdFxXSqaS_6-6k7FdGj5UVkhDmhBmHnRf7lm8lANEwsT1aMm8xYAlZGEcbWCr80S5XF9hqE-WmOe8-OqqAf2R4PrEmxUXrvTWEKIX2MJIDcZJf0vbU39hvcgIdrPqJ2UZcxkltvu-fxhHQqOc54oQOa24WdyELA9f8ybT3hM2nwZ8PH6bz1uaGFzYk4X5LjyvwkCB76yaJv_scMOgniMWQfKXMiRHQ44BOGaybHyJtf7jEvv4NPmQUH8rTUM7pvKBLRb2t-5K-QfcSAdpH1O5B2RdeqtqOflXvO2_aRdm1rEaGqHRbGYHRDH22u3dfyb3D_x04spgh5eeWXEzyfIDCDELoFBlxmTbtKbkOBKIWyvQBqVEkBj8PvUH2cbsvfM1mQP75jjI5DGfMJLSRSVgx-4jU-rpMKU7fN9fmye7mBalJzUvYgfVjemy_m18rxscTzJbKJcos7XlC7ZpDy5PJjpUMplcjXWYOB714FticxITdE621ij1qKBw-8V3ryoVa0RJ92F-HSHVrb9-V79EYU1sM2IenJ7kMprKN2TTvt2NkZ79UXlKctTh3jz_POwauKEtJh1qzM34ZntrHvZEzVyw

google.calendar.credentials-path=classpath:google/credentials.json
google.calendar.redirect-uri=http://localhost:8080/oauth/google-calendar/callback

email.enabled=true
email.host=smtp.gmail.com
email.port=587
email.authentication=true
email.starttls=true
security.encryption.secret=a-very-long-random-secret-key-32-chars
security.encryption.salt=936a371b23a5b0efbd313dcd55b018c3

telegram.enabled=true
telegram.bot-token=${TELEGRAM_BOT_TOKEN}

jwt.secret=ThisIsAVeryLongSecretKeyForJWTGenerationQwertyY4321
jwt.expiration=604800000
